name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Push the Docker image
      run: docker build . --file Dockerfile --tag vitexsoftware/multiflexi-demo:${{github.run_number}}
    - name: Push the Docker image to Docker Hub
      run: docker push vitexsoftware/multiflexi-demo:${{github.run_number}}
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
