name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vitexsoftware/multiflexi-demo:$(date +%s)

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Push the Docker image to Docker Hub
      run: docker push vitexsoftware/multiflexi-demo:$(date +%s)
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
